################################################################################
#
# Title:        ONTAP-revert-53 - Backup (SnapMirror S3)
# Author:       NetApp Inc. (jont)
# Initial 
# Create Date:  2025-04-24
# Description:  Revert all steps performed in test frame 53
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################


- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-revert-53 - Backup (SnapMirror S3) - ONTAP Secondary"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  - name: Delete SnapMirror S3 relationship
    netapp.ontap.na_ontap_rest_cli:
      command: snapmirror
      verb: DELETE
      body:
        source_path: "{{ global_primary_nas_svm }}:/bucket/{{ ontap_53_s3_bucket_name }}"
        destination_path: "{{ global_primary_backup_svm }}:/bucket/{{ ontap_53_s3_bucket_name }}"

  - name: Delete SnapMirror custom policy
    netapp.ontap.na_ontap_rest_cli:
      command: snapmirror/policy
      verb: DELETE
      body:
        vserver: "{{ global_primary_nas_svm }}"
        policy: "{{ ontap_53_policy_name }}"


