################################################################################
#
# Title:        ONTAP-revert-33 - S3
# Author:       NetApp Inc. (jont)
# Initial 
# Create Date:  2025-04-24
# Description:  Revert all steps performed in test frame 33
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################


- hosts:                               "ontap"
  name:                                "ONTAP-revert-33 - S3"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Remove S3 buckets
      netapp.ontap.na_ontap_s3_buckets:
        state: absent
        name: "{{ ontap_33_s3_bucket_name }}"
        size: "{{ ontap_33_s3_bucket_size }}"
        vserver: "{{ item.svm.name }}"
      loop:
        "{{ protocols_s3_services }}"
      loop_control:
        label: "{{ item.svm.name }}"
      when:
        - protocols_s3_services | length > 0
        - item.name is defined
        - item.svm.name is regex('^ntap-svm.*')

    - name: Remove S3 users
      netapp.ontap.na_ontap_s3_users:
        state: absent
        name: "{{ ontap_33_s3_user_name }}"
        vserver: "{{ item.svm.name }}"
      loop:
       "{{ protocols_s3_services }}"
      loop_control:
        label: "{{ item.svm.name }}"
      when:
        - protocols_s3_services | length > 0
        - item.name is defined
        - item.svm.name is regex('^ntap-svm.*')

    - name: Remove S3 groups
      netapp.ontap.na_ontap_s3_groups:
        state: absent
        name: "{{ ontap_33_s3_group_name }}"
        vserver: "{{ item.svm.name }}"
        users:
          - name: "{{ ontap_33_s3_user_name }}"
        policies:
          - name: "{{ ontap_33_s3_group_policy }}"
      loop:
       "{{ protocols_s3_services }}"
      loop_control:
        label: "{{ item.svm.name }}"
      when:
        - protocols_s3_services | length > 0
        - item.name is defined
        - item.svm.name is regex('^ntap-svm.*')
        
  post_tasks:
