################################################################################
#
# Title:        ONTAP-33-01 - Create S3 User and Group
# Author:       NetApp Inc. (jont)
# Initial
# Create Date:  2025-04-10
# Description:  Create an S3 User and Group
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "ontap"
  name:                                "ONTAP-33-01 - Create S3 User and Group"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create or regenerate S3 users and return access tokens
      include_tasks: Tasks-33-01.yml
      loop:
       "{{ protocols_s3_services }}"
      loop_control:
        label: "{{ item.svm.name }}"
      when:
        - protocols_s3_services | length > 0
        - item.name is defined
        - item.svm.name is regex('^ntap-svm.*')

    - name: Create S3 Groups
      netapp.ontap.na_ontap_s3_groups:
        state: present
        name: "{{ ontap_33_s3_group_name }}"
        vserver: "{{ item.svm.name }}"
        users:
          - name: "{{ ontap_33_s3_user_name }}"
        policies:
          - name: "{{ ontap_33_s3_group_policy }}"
      loop:
       "{{ protocols_s3_services }}"
      loop_control:
        label: "{{ item.svm.name }}"
      when:
        - protocols_s3_services | length > 0
        - item.name is defined
        - item.svm.name is regex('^ntap-svm.*')

  post_tasks:
