################################################################################
#
# Title:        ONTAP-20-05 - Create Certificates and S3 Service
# Author:       NetApp Inc. (jont)
# Initial
# Create Date:  2025-04-08
# Description:  Create and install a self-signed server security certificate
#               - Create the root-ca
#               - Generate a certificate signing request
#               - Sign the request using the local root-ca
#               - install the signed certificate
#               - Use the new server cert to create the S3 server
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "ontap"
  name:                                "ONTAP-20-05 - Create Certificates and S3 Service"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create SVM self-signed certificates
      include_tasks: Tasks-20-05-01.yml
      loop:
       "{{ svm_svms }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - svm_svms | length > 0
        - item.name is defined
        - item.name is regex('^ntap-svm.*')

    - name: Create S3 Servers
      include_tasks: Tasks-20-05-02.yml
      loop:
       "{{ protocols_s3_services }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - protocols_s3_services | length > 0
        - item.name is defined
        - item.svm.name is regex('^ntap-svm.*')

  post_tasks:
