################################################################################
#
# Title:        ONTAP-34-07 - Create S3 user and group
# Author:       NetApp Inc. (jont)
# Initial
# Create Date:  2025-04-28
# Description:  Create S3 user and group
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-34-05 - Create S3 user and group"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:

    - name: Create or regenerate the S3 user
      netapp.ontap.na_ontap_s3_users:
        state: present
        name: "{{ ontap_34_s3_user_name }}"
        vserver: "{{ global_primary_nas_svm }}"
        regenerate_keys: true
      register: s3_user
  
    - name: Debug information about the S3 user
      debug:
        var: s3_user
        
    - name: Create S3 groups
      netapp.ontap.na_ontap_s3_groups:
        state: present
        name: "{{ ontap_34_s3_group_name }}"
        vserver: "{{ global_primary_nas_svm }}"
        users:
          - name: "{{ ontap_34_s3_user_name }}"
        policies:
          - name: "{{ ontap_34_s3_group_policy }}"

  post_tasks:
