################################################################################
#
# Title:        ONTAP-revert-34 - Multiprotocol
# Author:       NetApp Inc. (jont)
# Initial 
# Create Date:  2025-04-30
# Description:  Revert all steps performed in test frame 34
# 
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
# 
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
#
################################################################################

- hosts:                               "windows_hosts"
  name:                                "ONTAP-revert-34 - Multiprotocol"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.windows
    - community.windows

  pre_tasks:

  tasks:
    - name: 
      block:
        - name: Remove mapped shares
          community.windows.win_shortcut:
            state:                     absent
            dest:                      "{{ windows_34_mount_dir }}\\{{ item }}.lnk"
          loop:
            "{{ ontap_34_fg_unix_qtree_names + 
                ontap_34_fg_ntfs_qtree_names + 
                ontap_34_fg_mixed_qtree_names }}"

        - name: Remove network credentials
          community.windows.win_credential:
            state:                     absent
            name:                      "{{ global_primary_nas_svm }}"
            type:                      "domain_password"
      vars:
        # become is required to save and retrieve the credentials in the tasks
        ansible_become:                "yes"
        ansible_become_method:         "runas"
        ansible_become_user:           "{{ ansible_user }}"
        ansible_become_pass:           "{{ ansible_password }}"

    - name: Remove credentials directory
      ansible.windows.win_file:
        path:                          "{{ windows_default_mount_dir }}/s3_credentials/"
        state:                         absent
        
    - name: Remove mount directory
      ansible.windows.win_file:
        path:                          "{{ windows_34_mount_dir }}"
        state:                         absent

- hosts:                               "linux"
  name:                                "ONTAP-revert-34 - Multiprotocol"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - ansible.posix

  tasks:
    - name: Unmount exports on FlexGroup
      ansible.posix.mount:
        state:                         "absent"
        src:                           "{{ global_primary_nas_svm }}.{{ all_default_dns_domain }}:/{{ ontap_34_fg_name }}/{{ item }}"
        path:                          "{{ linux_34_mount_dir }}/{{ item }}"
        fstype:                        "nfs"
      loop:
        "{{ ontap_34_fg_unix_qtree_names +
            ontap_34_fg_ntfs_qtree_names +
            ontap_34_fg_mixed_qtree_names }}"
  
    - name: Remove mount directories
      ansible.builtin.file:
        path:                          "{{ linux_34_mount_dir }}/{{ item }}"
        state:                         "absent"
        mode:                          "0755"
      loop:
        "{{ ontap_34_fg_unix_qtree_names +
            ontap_34_fg_ntfs_qtree_names +
            ontap_34_fg_mixed_qtree_names }}"

    - name: Remove default parent mount directory
      ansible.builtin.file:
        path:                          "{{ linux_34_mount_dir }}"
        state:                         "absent"
        mode:                          "0755"

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-revert-34 - Multiprotocol"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Remove shares
      netapp.ontap.na_ontap_cifs:
        state:                         absent
        name:                          "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
      loop:
        "{{ ontap_34_fg_unix_qtree_names + 
            ontap_34_fg_ntfs_qtree_names + 
            ontap_34_fg_mixed_qtree_names }}"

    - name: Remove S3 buckets
      netapp.ontap.na_ontap_s3_buckets:
        state: absent
        name: "{{ ontap_34_s3_bucket_name }}"
        type: nas
        nas_path: "/{{ ontap_34_fg_name }}"
        vserver: "{{ global_primary_nas_svm }}"

    - name: Remove S3 users
      netapp.ontap.na_ontap_s3_users:
        state: absent
        name: "{{ ontap_34_s3_user_name }}"
        vserver: "{{ global_primary_nas_svm }}"

    - name: Remove S3 groups
      netapp.ontap.na_ontap_s3_groups:
        state: absent
        name: "{{ ontap_34_s3_group_name }}"
        vserver: "{{ global_primary_nas_svm }}"
        users:
          - name: "{{ ontap_34_s3_user_name }}"
        policies:
          - name: "{{ ontap_34_s3_group_policy }}"
          
    - name: Remove FlexGroup
      netapp.ontap.na_ontap_volume:
        state:                         absent
        name:                          "{{ ontap_34_fg_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"
  
    - name: Remove read-write export policy
      netapp.ontap.na_ontap_export_policy:
        state:                         absent
        name:                          "{{ ontap_34_policy_name }}"
        vserver:                       "{{ global_primary_nas_svm }}"

    - name: Remove Windows admin user -> UNIX root name mapping configuration
      netapp.ontap.na_ontap_name_mappings:
        state:                         absent
        direction:                     win_unix
        index:                         1
        vserver:                       "{{ global_primary_nas_svm }}"

    - name: Remove UNIX root -> Windows admin user name mapping configuration
      netapp.ontap.na_ontap_name_mappings:
        state:                         absent
        direction:                     unix_win
        index:                         1
        vserver:                       "{{ global_primary_nas_svm }}"

    - name: Remove S3-UNIX name mapping configuration
      netapp.ontap.na_ontap_name_mappings:
        state:                         absent
        direction:                     s3_unix
        index:                         1
        pattern:                       "{{ ontap_34_s3_user_name }}"
        replacement:                   "root"
        vserver:                       "{{ global_primary_nas_svm }}"

    - set_fact: 
        admin_user:                    "{{ ontap_34_ad_admin_user | replace(match, replace) }}"
      vars:
        match:                         '\'
        replace:                       '\\'
        
    - name: Remove S3-SMB name mapping configuration
      netapp.ontap.na_ontap_name_mappings:
        state:                         absent
        direction:                     s3_win
        index:                         2
        pattern:                       "{{ ontap_34_s3_user_name }}"
        replacement:                   "{{ admin_user }}"
        vserver:                       "{{ global_primary_nas_svm }}"
  
  post_tasks:
