################################################################################
#
# Title:        ONTAP-34-10 - Objects
# Author:       NetApp Inc. (jont)
# Initial
# Create Date:  2025-05-05
# Description:  S3
#               - Objects
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc amazon.aws.<module_name>
#
################################################################################

- hosts:                               "localhost"
  name:                                "ONTAP-34-10 - Objects"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ ansible_inventory_sources[-1] | split('/') | last }}/vars.yml
    - ../../vars/{{ ansible_inventory_sources[-1] | split('/') | last }}/vault.yml
  collections:
    - amazon.aws

  pre_tasks:

  tasks:
    - name: Read S3 credentials
      ansible.builtin.include_vars:
        dir:                           "{{ linux_default_mount_dir }}/.s3_credentials"
        name:                          s3_credentials

    - name: Simple PUT operation
      amazon.aws.s3_object:
        bucket:                        "{{ ontap_34_s3_bucket_name }}"
        object:                        "cluster1"
        src:                           "{{ linux_default_mount_dir }}/.s3_credentials/{{ ontap_34_s3_user_name }}.json"
        mode:                          put
        permission:                    []
        endpoint_url:                  "https://{{ global_primary_nas_svm }}.demo.netapp.com"
        access_key:                    "{{ s3_credentials.access_key }}"
        secret_key:                    "{{ s3_credentials.secret_key }}"
        validate_certs:                false

    - name: Get bucket content
      amazon.aws.s3_object_info:
        bucket_name:                   "{{ ontap_34_s3_bucket_name }}"
        endpoint_url:                  "https://{{ global_primary_nas_svm }}.demo.netapp.com"
        access_key:                    "{{ s3_credentials.access_key }}"
        secret_key:                    "{{ s3_credentials.secret_key }}"
        validate_certs:                false
      register: object_info

    - name: List bucket content
      ansible.builtin.debug:
        msg: "{{ object_info }}"

  post_tasks:
  
