################################################################################
#
# Title:        ONTAP-34-05 - Shares & ACLs (Multiprotocol)
# Author:       NetApp Inc. (jont)
# Initial 
# Create Date:  2025-04-29
# Description:  CIFS
#               - Shares & ACLs (FlexGroup)
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:                               "primary_storage_clusters"
  name:                                "ONTAP-34-05 - Shares & ACLs (Multiprotocol)"
  gather_facts:                        false
  vars_files:
    - ../../vars/{{ inventory_dir | split('/') | last }}/vars.yml
    - ../../vars/{{ inventory_dir | split('/') | last }}/vault.yml
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname:                        "{{ ansible_host }}"
      username:                        "{{ ontap_admin_user }}"
      password:                        "{{ ontap_admin_password }}"
      https:                           true
      validate_certs:                  false
      use_rest:                        "always"

  pre_tasks:

  tasks:
    - name: Create shares
      netapp.ontap.na_ontap_cifs:
        state:                         present
        name:                          "{{ item }}"
        path:                          "/{{ ontap_34_fg_name }}/{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        browsable:                     true
        oplocks:                       true
        show_snapshot:                 true
        comment:                       "Test share created as part of test frame ONTAP-34"
      loop:
        "{{ ontap_34_fg_unix_qtree_names + ontap_34_fg_ntfs_qtree_names + ontap_34_fg_mixed_qtree_names}}"

    - name: Remove "Full Control" for "Everyone"
      netapp.ontap.na_ontap_cifs_acl:
        state:                         absent
        share_name:                    "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        user_or_group:                 "Everyone"
        permission:                    "full_control"
      loop:
        "{{ ontap_34_fg_unix_qtree_names + ontap_34_fg_ntfs_qtree_names + ontap_34_fg_mixed_qtree_names}}"

    - name: Create ACL on test share (admins - Full Control)
      netapp.ontap.na_ontap_cifs_acl:
        state:                         present
        share_name:                    "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        user_or_group:                 "{{ ontap_34_ad_admin_group }}"
        permission:                    "full_control"
      loop:
        "{{ ontap_34_fg_unix_qtree_names + ontap_34_fg_ntfs_qtree_names + ontap_34_fg_mixed_qtree_names}}"

    - name: Create ACL on test share (read-only users - Read)
      netapp.ontap.na_ontap_cifs_acl:
        state:                         present
        share_name:                    "{{ item }}"
        vserver:                       "{{ global_primary_nas_svm }}"
        user_or_group:                 "{{ ontap_34_ad_ro_group }}"
        permission:                    "read"
      loop:
        "{{ ontap_34_fg_unix_qtree_names + ontap_34_fg_ntfs_qtree_names + ontap_34_fg_mixed_qtree_names}}"

  post_tasks:
